---
#Spanning Tree Configuration
spanning_tree:
  mode: mst
  priority: "4096"

#Physical Interfaces
spine_interfaces:
- name: "Ethernet3"
  peer: "karlo-cn-spine-02"
  channel: "70"
- name: "Ethernet4"
  peer: "karlo-cn-spine-02"
  channel: "70"
- name: "Ethernet5"
  peer: "karlo-cn-leaf-01"
  channel: "10"
- name: "Ethernet6"
  peer: "karlo-cn-leaf-02"
  channel: "20"

#MLAG Configuration
mlag:
  ip: "10.0.70.1/30"
  peer_ip: "10.0.70.2"

# Global VARP MAC Address
varp_mac_address: "00:1c:73:00:00:01"

svi_interfaces:
  # --- MLAG Peer Link SVI ---
  - vlan: "70"
    description: "SPINE MLAG PEER"
    ip_address: "10.0.70.1/30"
    autostate: false
  
  # --- VARP Gateway SVIs ---
  - vlan: "10"
    description: "INFRA-MGMT"
    ip_address: "10.0.10.1/24"
    varp_ip: "10.0.10.254"
  - vlan: "11"
    description: "SRV-MGMT"
    ip_address: "10.0.11.1/24"
    varp_ip: "10.0.11.254"
  - vlan: "20"
    description: "WIN-CLIENTS"
    ip_address: "10.0.20.1/24"
    varp_ip: "10.0.20.254"
  - vlan: "21"
    description: "LIN-CLIENTS"
    ip_address: "10.0.21.1/24"
    varp_ip: "10.0.21.254"
  - vlan: "30"
    description: "SEC-APPS"
    ip_address: "10.0.30.1/24"
    varp_ip: "10.0.30.254"
  - vlan: "40"
    description: "DMZ"
    ip_address: "10.0.40.1/24"
    varp_ip: "10.0.40.254"
  - vlan: "50"
    description: "PRD-SVRS"
    ip_address: "10.0.50.1/24"
    varp_ip: "10.0.50.254"
  - vlan: "60"
    description: "BACKUPS"
    ip_address: "10.0.60.1/24"
    varp_ip: "10.0.60.254"
    