---
- name: "North Star | Router Playbook"
  hosts: vyos_routers
  gather_facts: false

  tasks:
### Device Configuration settings ###
    - name: "Configure Banner"
      vyos.vyos.vyos_banner:
        banner: pre-login
        text: |
          ======================================================================
          NORTH STAR LAB
          UNAUTHORIZED ACCESS TO THIS NETWORK DEVICE IS STRICTLY PROHIBITED
          Do not proceed unless are your authorized to access this environment
          ======================================================================
        state: present

    - name: "Configure SSH and Security Hardening"
      vyos.vyos.vyos_config:
        lines:
          - delete service telnet
          - set service ssh access-control deny user root
          - set service ssh client-keepalive-interval "300"

    - name: "Management ACL to allow access from Ansible host only"
      vyos.vyos.vyos_config:
        lines:
          - set firewall group address-group MGT address "10.0.10.253"
          - set firewall ipv4 input filter rule 10 action "accept"
          - set firewall ipv4 input filter rule 10 destination port "22"
          - set firewall ipv4 input filter rule 10 protocol "tcp"
          - set firewall ipv4 input filter rule 10 source group address-group "MGT"
          - set firewall ipv4 input filter rule 10 action "accept"      
          - set firewall ipv4 input filter rule 20 action "drop"
          - set firewall ipv4 input filter rule 20 destination port "22"
          - set firewall ipv4 input filter rule 20 protocol "tcp"
          - set firewall ipv4 input filter rule 20 action "drop"     
          - set firewall ipv4 input filter default-action "accept"

#### Configure Physical Interfaces Description and MTU ###
    - name: "Configure Physical Interfaces"
      vyos.vyos.vyos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
        state: merged
      loop: "{{ router_interfaces }}"

### Configure the physical interfaces into Bond0 LAG Interface ###
    - name: "Create Router Bond0 Interface"
      vyos.vyos.vyos_lag_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: "{{ item.mode }}"
            members:
              - member: "eth8"
              - member: "eth9"
        state: merged
      loop: "{{ router_lag_interfaces }}"

    - name: "Configure LAG Description"
      vyos.vyos.vyos_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
        state: merged
      loop: "{{ router_lag_interfaces }}"

### Configure IP addresses on the physical and Lag Interfaces ###
    - name: "Assign IP addresses to Router Interfaces"
      vyos.vyos.vyos_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip_address }}"
        state: merged
      loop: "{{ router_interfaces }}"

    - name: "Assign IP address to Router LAG Interface"
      vyos.vyos.vyos_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ip_address }}"
        state: merged
      loop: "{{ router_lag_interfaces }}"

### Configure Global and Interface OSPF Parameters ###
    - name: "Configure OSPF Area on Interfaces"
      vyos.vyos.vyos_ospfv2:
        config :
          parameters:
            router_id: "{{ OSPF.router_id }}"
        state: merged
          
    - name: "Configure OSPF Area on Interfaces"
      vyos.vyos.vyos_config:
        lines:
          - set protocols ospf interface eth1 area '0'
          - set protocols ospf interface eth2 area '0'
          - set protocols ospf interface eth4 area '0'
          - set protocols ospf interface eth5 area '0'
          - set protocols ospf interface bond0 area '0'
          - set protocols ospf interface lo area '0'

    - name: "Configure OSPF Network Type on Interfaces"
      vyos.vyos.vyos_config:
        lines:
          - set protocols ospf interface eth1 network 'point-to-point'
          - set protocols ospf interface eth2 network 'point-to-point'
          - set protocols ospf interface eth4 network 'point-to-point'
          - set protocols ospf interface eth5 network 'point-to-point'
          - set protocols ospf interface bond0 network 'point-to-point'
