---
- name: Deploy Spines & Access Leafs Underlay
  hosts: arista_spine_switches
  gather_facts: false
  tasks:
    - name: Configure Loopback0
      arista.eos.eos_config:
        parents: interface Loopback0
        lines:
          - description EVPN-VTEP-SOURCE
          - ip address {{ loopback_ip }}
          - ip ospf area 0.0.0.0

    - name: Configure Point-to-Point links
      arista.eos.eos_config:
        parents: "interface {{ item.name }}"
        lines:
          - description {{ item.desc }}
          - no switchport
          - mtu 9214
          - ip address {{ item.ip }}
          - ip ospf network point-to-point
          - ip ospf area 0.0.0.0
      loop: "{{ fabric_interfaces }}"

    - name: Configure Global OSPF Process
      arista.eos.eos_config:
        parents: router ospf 1
        lines:
          - router-id {{ router_id }}
          - passive-interface default
          - "no passive-interface {{ item.name }}"
          - max-lsa 12000
      loop: "{{ fabric_interfaces }}"

