---
- name: Deploy Phase 1 - VyOS Border Leafs
  hosts: vyos
  gather_facts: no
  tasks:
    - name: Disable OSPF
      vyos.vyos.vyos_config:
        lines:
          - delete protocols ospf

    - name: Configure Dummy Interface
      vyos.vyos.vyos_config:
        lines:
          - set interfaces dummy dum0 address '{{ loopback_ip }}/32'

    - name: Configure Transit Physical Interfaces
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet {{ item.name }} description '{{ item.desc }}'
          - set interfaces ethernet {{ item.name }} address '{{ item.ip }}'
          - set interfaces ethernet {{ item.name }} mtu '9214'
      loop: "{{ interfaces }}"
      when: "'fw' not in item.desc"

    - name: Configure Firewall Physical Interfaces (Standard MTU)
      vyos.vyos.vyos_config:
        lines:
          - set interfaces ethernet {{ item.name }} description '{{ item.desc }}'
          - set interfaces ethernet {{ item.name }} address '{{ item.ip }}'
      loop: "{{ interfaces }}"
      when: "'fw' in item.desc"

    - name: Configure Base BGP and Peer Groups
      vyos.vyos.vyos_config:
        lines:
          - set protocols bgp system-as {{ bgp_asn }}
          - set protocols bgp parameters router-id '{{ loopback_ip }}'
          - set protocols bgp peer-group UNDERLAY remote-as external
          - set protocols bgp peer-group EVPN_OVERLAY ebgp-multihop 3
          - set protocols bgp peer-group EVPN_OVERLAY update-source {{ loopback_ip }}

    - name: Configure Underlay BGP Neighbors
      vyos.vyos.vyos_config:
        lines:
          - set protocols bgp neighbor {{ item.ip }} peer-group UNDERLAY
      loop: "{{ underlay_peers }}"

    - name: Configure Overlay BGP Neighbors
      vyos.vyos.vyos_config:
        lines:
          - set protocols bgp neighbor {{ item.ip }} peer-group EVPN_OVERLAY
          - set protocols bgp neighbor {{ item.ip }} remote-as {{ item.asn }}
      loop: "{{ overlay_peers }}"

    - name: Configure BGP Address Families
      vyos.vyos.vyos_config:
        lines:
          - set protocols bgp address-family ipv4-unicast network {{ loopback_ip }}/32
          - set protocols bgp peer-group EVPN_OVERLAY address-family l2vpn-evpn