---
spanning_tree_mode: mst
spanning_tree_priority: "12288"

leaf_interfaces:
- name: "ethernet5"
  peer: "karlo-vulcan-sp-01"
  channel: "10"
  mode: "trunk"
- name: "ethernet9"
  peer: "karlo-vulcan-sp-02"
  channel: "10"
  mode: "trunk"


leaf_interfaces_access:
- name: "ethernet 12"
  peer: "karlo-vulcan-win10"
  mode: "access"
  vlan: "30"