---
- name: Deploy Phase 1 - All Switches
  hosts: arista_switches
  gather_facts: no
  tasks:
    - name: Disable OSPF
      arista.eos.eos_config:
        lines:
          - no router ospf 1

    - name: Enable Multi-Agent Routing
      arista.eos.eos_config:
        lines:
          - service routing protocols model multi-agent

### Configure the loop back address for all devices in the fabric
    - name: Configure Loopback0
      arista.eos.eos_config:
        parents: interface Loopback0
        lines:
          - description EVPN Loopback
          - ip address {{ loopback_ip }}/32

### Configure VTEP for Access Leafs only
    - name: Configure VXLAN VTEP
      arista.eos.eos_config:
        parents: interface Vxlan1
        lines:
          - vxlan source-interface Loopback0
          - vxlan udp-port 4789
      when: "'al' in inventory_hostname"

### Configure physical interfaces
    - name: Configure PTP Physical Interfaces
      arista.eos.eos_config:
        parents: interface {{ item.name }}
        lines:
          - description {{ item.desc }}
          - no switchport
          - mtu 9214
          - ip address {{ item.ip }}
      loop: "{{ interfaces }}"

    - name: Configure BGP
      arista.eos.eos_config:
        parents: router bgp {{ bgp_asn }}
        lines:
          - router-id {{ loopback_ip }}
          - maximum-paths 4 ecmp 4
          - neighbor UNDERLAY peer group
          - neighbor UNDERLAY send-community
          - neighbor EVPN_OVERLAY peer group
          - neighbor EVPN_OVERLAY update-source Loopback0
          - neighbor EVPN_OVERLAY ebgp-multihop 3
          - neighbor EVPN_OVERLAY send-community

### Configure setting for spines only to stop it from changing the return address to itself
    - name: Apply Next-Hop-Unchanged
      arista.eos.eos_config:
        parents: router bgp {{ bgp_asn }}
        lines:
          - neighbor EVPN_OVERLAY next-hop-unchanged
      when: "'sp' in inventory_hostname"

    - name: Configure Underlay BGP Neighbors
      arista.eos.eos_config:
        parents: router bgp {{ bgp_asn }}
        lines:
          - neighbor {{ item.ip }} peer group UNDERLAY
          - neighbor {{ item.ip }} remote-as {{ item.asn }}
      loop: "{{ underlay_peers }}"

    - name: Configure Overlay BGP Neighbors
      arista.eos.eos_config:
        parents: router bgp {{ bgp_asn }}
        lines:
          - neighbor {{ item.ip }} peer group EVPN_OVERLAY
          - neighbor {{ item.ip }} remote-as {{ item.asn }}
      loop: "{{ overlay_peers }}"

    - name: Configure BGP Address Families
      arista.eos.eos_config:
        parents: 
          - router bgp {{ bgp_asn }}
          - address-family ipv4
        lines:
          - neighbor UNDERLAY activate
          - network {{ loopback_ip }}/32
        match: exact
    
    - name: Configure EVPN Address Family
      arista.eos.eos_config:
        parents: 
          - router bgp {{ bgp_asn }}
          - address-family evpn
        lines:
          - neighbor EVPN_OVERLAY activate